pcall(require, "luacov")

local testing = require("ascii-ui.testing")
local ui = require("ascii-ui")
local ScoreDisplay = require("simon-says.components.score-display")

describe("ScoreDisplay", function()
	it("renders score and high score", function()
		local App = ui.createComponent("App", function()
			return ScoreDisplay({ score = 3, highScore = 5 })
		end)
		local screen = testing.render(App)
		assert(screen:hasText("3"))
		assert(screen:hasText("5"))
	end)

	it("renders labels", function()
		local App = ui.createComponent("App", function()
			return ScoreDisplay({ score = 0, highScore = 0 })
		end)
		local screen = testing.render(App)
		assert(screen:hasText("Score:"))
		assert(screen:hasText("High Score:"))
	end)
end)
