pcall(require, "luacov")

local testing = require("ascii-ui.testing")
local ui = require("ascii-ui")
local StatusMessage = require("simon-says.components.status-message")

describe("StatusMessage", function()
	it("shows start message when idle", function()
		local App = ui.createComponent("App", function()
			return StatusMessage({ gamePhase = "idle", playerIndex = 0, sequenceLength = 0, score = 0 })
		end)
		local screen = testing.render(App)
		assert(screen:hasText("Press any quadrant to start"))
	end)

	it("shows watch message when showing", function()
		local App = ui.createComponent("App", function()
			return StatusMessage({ gamePhase = "showing", playerIndex = 0, sequenceLength = 3, score = 0 })
		end)
		local screen = testing.render(App)
		assert(screen:hasText("Watch"))
	end)

	it("shows progress when input", function()
		local App = ui.createComponent("App", function()
			return StatusMessage({ gamePhase = "input", playerIndex = 1, sequenceLength = 3, score = 2 })
		end)
		local screen = testing.render(App)
		assert(screen:hasText("Your turn"))
		assert(screen:hasText("1"))
		assert(screen:hasText("3"))
	end)

	it("shows game over message", function()
		local App = ui.createComponent("App", function()
			return StatusMessage({ gamePhase = "gameover", playerIndex = 0, sequenceLength = 3, score = 5 })
		end)
		local screen = testing.render(App)
		assert(screen:hasText("Game Over"))
		assert(screen:hasText("5"))
	end)

	it("shows play again message on game over", function()
		local App = ui.createComponent("App", function()
			return StatusMessage({ gamePhase = "gameover", playerIndex = 0, sequenceLength = 3, score = 5 })
		end)
		local screen = testing.render(App)
		assert(screen:hasText("Press any quadrant to play again"))
	end)
end)
