pcall(require, "luacov")

local testing = require("ascii-ui.testing")
local ui = require("ascii-ui")
local Title = require("simon-says.components.title")

describe("Title", function()
	it("renders game title", function()
		local App = ui.createComponent("App", function()
			return Title()
		end)
		local screen = testing.render(App)
		assert(screen:hasText("SIMON SAYS"))
	end)

	it("renders border characters", function()
		local App = ui.createComponent("App", function()
			return Title()
		end)
		local screen = testing.render(App)
		assert(screen:hasText("╔"))
		assert(screen:hasText("╝"))
	end)
end)
